config/routes.rb
MentorPairing::Application.routes.draw do
  get "/activations/:code/user", :to => "activations#user"
  get "/appointments/:code/create", :to => "appointments#create"
  post "/users/findmentor", :to => "users#find_mentor"
  root :to => "availabilities#index"

  resources :availabilities
  resources :users
  resources :appointment_requests
end

app/models/appointment_request.rb
class AppointmentRequest < ActiveRecord::Base
  belongs_to :mentee, :class_name => "User"
  belongs_to :availability

  validates_presence_of :mentee_id, :availability_id
end

app/controllers/appointment_requests_controller.rb
class AppointmentRequestsController < ApplicationController
  def new
    @availability = Availability.find_by_id(params[:availability_id])
    return redirect_to availabilities_path unless @availability.present?
  end

  def create
    @availability = Availability.find_by_id(params[:availability_id])
    mentee = User.find_by_email(params[:email])

    if mentee && mentee.activated?
      flash[:notice] = "An email has been sent to #{@availability.mentor.first_name}. Once they confirm the appointment, we'll let you know."
      AppointmentRequest.create!(:mentee => mentee, :availability => @availability)
      mentee.send_appointment_request(@availability)
      redirect_to root_path
      return
    end

    if mentee.nil?
      mentee = User.create!(user_params)
    end

    mentee.send_activation
    flash.now[:notice] = "Please go check your email, ok? Then come back and re-submit."
    render :new
  end
end

app/views/appointment_requests/new.html.erb
<h2>Sign up</h2>

<div class="panel">
	<p>With <%= link_to_user(@availability.mentor) %> on <%= display_availability(@availability) %></p>

	<%= form_tag appointment_requests_path(:availability_id => @availability) do %>
	<p>Name <%= text_field_tag :first_name, params[:first_name] %><%= text_field_tag :last_name, params[:last_name] %></p>
	<p>Twitter handle <%= text_field_tag :twitter_handle, params[:twitter_handle] %></p>
	<p>Email address <%= text_field_tag :email, params[:email] %></p>
	<input type="submit" />
	<% end %>
</div>