config/routes.rb
MentorPairing::Application.routes.draw do
  get "/activations/:code/user", :to => "activations#user"
  get "/appointments/:code/create", :to => "appointments#create"
  post "/users/findmentor", :to => "users#find_mentor"
  root :to => "availabilities#index"

  resources :availabilities
  resources :users
  resources :appointment_requests
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
  has_many :availabilities, :foreign_key => :mentor_id
  has_many :mentoring_appointments, :foreign_key => :mentor_id, :class_name => "Appointment"
  has_many :menteeing_appointments, :foreign_key => :mentee_id, :class_name => "Appointment"
  has_many :appointment_requests, :foreign_key => :mentee_id
  has_many :received_kudos, :foreign_key => :mentor_id, :class_name => 'Kudo'
  has_many :given_kudos, :foreign_key => :mentee_id, :class_name => 'Kudo'

  validates_uniqueness_of :email

  before_create :create_activation_code

  def self.featured_mentors
    limit(10).order("total_kudos DESC")
  end

  def name
    [first_name, last_name].compact.join(" ")
  end

  def send_activation
    UserMailer.user_activation(self).deliver
    self
  end

  def send_appointment_request(availability)
    UserMailer.appointment_request(availability, self).deliver
  end

  def send_appointment_confirmation(appointment)
    UserMailer.appointment_confirmation(appointment).deliver
  end

  private

  def create_activation_code
    self.activation_code = Digest::MD5.hexdigest( rand.to_s + Time.now.to_s + (twitter_handle || ""))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find_by_activation_code(params[:id])
    @availabilities = @user.availabilities.visible.order(:start_time)
    @menteeing_appointments = @user.menteeing_appointments.order(:start_time)
    @mentoring_appointments = @user.mentoring_appointments.order(:start_time)
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end

  def find_mentor
      user = User.find_by_email(params[:email])

      respond_to do |format|
        format.json do
          if user
            render :json => { :first_name => user.first_name,
                              :last_name => user.last_name,
                              :twitter_handle => user.twitter_handle,
                              :bio => user.bio,
                              :interests => user.interests}
          else
            render :json => { :no_user => true }
          end
        end
      end
  end
end

app/views/users/_calendar.html.erb
<div id="calendar">
  <%= month_link("<", @date.beginning_of_month-1) %>
  <%= html_escape @date.strftime("%B %Y") %>
  <%= month_link(">", @date.end_of_month+1) %>
  <%= calendar_for events, :year => @date.year, :month => @date.month do |calendar| %>
    <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')%>
    <%= calendar.day(:day_method => :start_time) do |date, appointments| %>
      <% if appointments.nil? %>
        <%= date.day %>
      <% else %>
        <%= date.day %>
        <ul class="daily_appointments">
        <% appointments.each do |appt| %>
          <li class="mentee_name"><%= appt.mentee.first_name %> <%= appt.mentee.last_name %></li>
        <% end %>
        </ul>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<button id="show-calendar" class="link">My Calendar</button>
<%= render partial: "calendar", :locals => {:events => @mentoring_appointments} %>
<% unless @availabilities.empty? %><h2>My upcoming availability</h2><% end %>
<% @availabilities.each do |a| %>
<div class="panel">
	<p>
	  On <%= display_availability(a) %>
	  <%= link_to "Delete!", availability_path(a), :method => :delete %>
	</p>
</div>
<% end %>

<% unless @menteeing_appointments.empty? %><h2>My upcoming appointments with mentors</h2><% end %>
<% @menteeing_appointments.each do |a| %>
<div class="panel">
	<p>
	  <%= display_appointment(a) %>
	</p>
</div>
<% end %>

<% unless @mentoring_appointments.empty? %><h2>My upcoming appointments with mentees</h2><% end %>
<% @mentoring_appointments.each do |a| %>
<div class="panel">
	<p>
	  <%= display_appointment(a) %>
	</p>
</div>
<% end %>

app/views/users/show.html.erb
<h2><%=@user.name%></h2>
<div class="panel profile">

  <div class="profile_pic_wrap left">
    <%= image_tag @user.gravatar_url, class: 'profpic' %>
  </div>

  <div class="profile_content_wrap right">
    <p>
      <a href=<%= href_to_twitters_user(@user) %>><%= "@#{@user.try(:twitter_handle)}" %><%= image_tag("twitter_black_logo.jpg")%></a>
    </p>

    <% if @user.bio %>
      <h4><%= @user.first_name %>'s bio:</h4>
      <blockquote>
        <%=  @user.bio%>
      </blockquote>
    <% end %>

    <% if @user.interests %>
      <h4>I'd like to mentor on these topics:</h4>
      <blockquote><%=  @user.interests %></blockquote>
    <% end %>
  </div>
</div>


<h2> Upcoming availabilities</h2>
<% @user.availabilities.visible.order("start_time").each do |a| %>
<div class="panel">
  <p>
    <span aria-hidden="true" class="icon" data-icon="&hearts;"></span>
    <%= link_to a.mentor.name, user_path(a.mentor) %>
    on <%= display_availability(a) %>
    <%= link_to "Sign up", new_appointment_request_path(:availability_id => a.id) %>
  </p>
</div>
<% end %>