config/routes.rb
MentorPairing::Application.routes.draw do
  get "/activations/:code/user", :to => "activations#user"
  get "/appointments/:code/create", :to => "appointments#create"
  post "/users/findmentor", :to => "users#find_mentor"
  root :to => "availabilities#index"

  resources :availabilities
  resources :users
  resources :appointment_requests
end

app/models/availability.rb
class Availability < ActiveRecord::Base
  attr_accessor :duration

  belongs_to :mentor, :class_name => "User"

  validates :start_time, :presence => true

  before_save :adjust_for_timezone
  before_save :set_end_time

  scope :visible, Proc.new {
    includes(:mentor).
    where("users.activated" => true).
    where("start_time > ?", Time.now)
  }

  private

  def adjust_for_timezone
    self.start_time = ActiveSupport::TimeZone.find_tzinfo(timezone).local_to_utc(start_time)
  end

  def set_end_time
    self.end_time = self.start_time + self.duration.to_i*60
  end

end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController

  def new
    @availability = Availability.new(:location => "Dev Bootcamp")
  end

  def create
    mentor = find_or_activate_by_email
    mentor.availabilities.create!(format_start_time(availability_params))
    redirect_to availabilities_path
  end

  def index
    @availabilities = Availability.visible.order(:start_time)
    @appointments = Appointment.visible.order(:start_time)
    @featured = User.featured_mentors

    respond_to do |format|
      format.html
      format.json { render :json => build_json(@availabilities) }
    end
  end

  def destroy
    Availability.destroy(params[:id])
    redirect_to :back
  end

  private

  def availability_params
    params.require(:availability).permit('start_time(1s)', 'start_time(4i)', 'start_time(5i)', :start_time, :duration, :timezone, :location)
  end

  def format_start_time(time_params)
    return time_params unless time_params['start_time(1s)']
    new_time_params = time_params.clone
    year, month, day = new_time_params.delete('start_time(1s)').split('-')
    new_time_params['start_time(1i)'] = year
    new_time_params['start_time(2i)'] = month
    new_time_params['start_time(3i)'] = day
    new_time_params
  end

  def build_json(availabilities)
    public_data = availabilities.map do |a|
      list = [:start_time, :end_time, :timezone, :location].map {|attr| [attr, a[attr]]}
      hash = Hash[list]
      hash[:mentor_name] = a.mentor.name
      hash[:mentor_url] = a.mentor.twitter_handle
      hash
    end

    json = public_data.to_json
    json = params[:callback] + "(" + json + ")" if params[:callback].present?
    json
  end
end

app/views/availabilities/index.html.erb
<!--
<h2>Upcoming Events</h2>
<div class="panel">
  <p><span aria-hidden="true" class="icon" data-icon="&hearts;"></span>Mock Interview Night in Chicago is Tuesday, September 24 from 5:30 until 7:30.  Email <a href="mailto:alex@devbootcamp.com">Alex</a> if you are avalible to help out with this event.</p>
</div>
-->

<div id="availabilities">
  <h2>Available Mentoring Opportunities</h2>

  <% if @availabilities.empty? %>
    <div class="panel">
  	  <p><span aria-hidden="true" class="icon" data-icon="&hearts;"></span> There isn't currently any upcoming mentoring availibility. <%= link_to "Offer to mentor someone!", new_availability_path %></p>
  	</div>
  <% end %>

  <% @availabilities.each do |a| %>
    <div class="panel">
    	<p>
    		<%= image_tag a.mentor.gravatar_url, :class => "left" %>
    		<span aria-hidden="true" class="icon" data-icon="&hearts;"></span>
    	  <%= link_to a.mentor.name, user_path(a.mentor) %>
    	  on <%= display_availability(a) %>
    	</p>
    	<p>
    		<%= link_to "Sign up", new_appointment_request_path(:availability_id => a.id) %>
    	</p>
    </div>
  <% end %>
</div>

<div id="appointments">
  <% unless @appointments.empty? %><h2>Upcoming Mentoring Appointments</h2><% end %>
  <div class="panel">
    <% @appointments.each do |a| %>
      <div class="appointment">
        <p>
          <%= link_to_user(a.mentor) %>
        </p>
        <p>
          <span aria-hidden="true" class="icon" data-icon="&hearts;"></span>
        </p>
        <p>
          <%= link_to_user(a.mentee) %>
        </p>
        <p>
          in <%= distance_of_time_in_words(Time.now, a.start_time) %> at <%= a.location %>
        </p>
      </div>
    <% end %>
  </div>
</div>

<div id="featured_mentors">
  <h2>Top Mentors</h2>
  <div class="panel">
  <% @featured.each do |user| %>
    <p>
      <span aria-hidden="true" class="icon" data-icon="&hearts;"></span>
      <%= link_to_user user %>
    </p>
  <% end %>
  </div>
</div>

app/views/availabilities/new.html.erb
<div class="tabs">
  <div id="basics" class="tab active">
    The Basics
  </div>
  <div id="more" class="tab">
    Tell Us More
  </div>
</div>

<div class="panel">
  <%= form_tag availabilities_path do %>
    <div class="field"><label>Email address</label><%= text_field_tag :email %></div>
    <div class="field"><label>Name</label><%= text_field_tag :first_name %><%= text_field_tag :last_name %></div>
    <div class="field"><label>Twitter handle<span class="addon">@</span></label><%= text_field_tag :twitter_handle %></div>

    <!-- optional/hidden form fields -->
    <div id="optional_fields" class="hidden">
      <div class="field">
        <label>Your tech interests</label>
        <%= text_field_tag :interests %>
      </div>

      <div class="field">
        <label>A brief bio</label>
        <textarea name="bio", id="bio"></textarea>
      </div>
    </div>

    <div class="field">
      <label>Date &amp; time available for mentoring</label>
      <%= text_field_tag 'availability[start_time_1s]', Date.current, :name => 'availability[start_time(1s)]' %>
      <%= time_select :availability, :start_time, :ignore_date => true %>
    </div>
    <div class="field"><label>Duration in minutes</label><%= text_field :availability, :duration %></div>
    <div class="field"><label>Timezone</label><%= time_zone_select(:availability, :timezone, ActiveSupport::TimeZone.us_zones, default: "Central Time (US & Canada)") %></div>
    <div class="field"><label>Location</label><%= text_field :availability, :location %></div>
    <input id="submit_availability" type="submit" />
  <% end %>
</div>